### ISSUE TITLE
Newly created survey behaves as a finalised survey

### ISSUE THREAD

**Issue by fvicino** [khyateh/lumstic-web#2]
Steps:
1. Log into survey web ( https://vast-savannah-30841.herokuapp.com/surveys ) as designer@foo.com
2. Create a new survey, add Survey name and description, save survey
3. Add a question of any type

Result:
System displays a message box "Are you sure you want to add a question to a finalised survey"
The Delete button is not visible.

Clicking ok allows the question to be created. This message is displayed for all questions created

Cannot reproduce in local environment

**Comment by anandeswara** [comment]
Resolved
