### ISSUE TITLE
Publishing a survey does not display allocation page

### ISSUE THREAD

**Issue by fvicino** [khyateh/lumstic-web#4]
Steps:
1. Log into survey web ( https://vast-savannah-30841.herokuapp.com/surveys ) as designer@foo.com
2. Create a new survey, add Survey name and description
3. Add a question of any type, save survey
4. Click the publish button, system displays confirmation message click ok

Result:
The survey appears to save, but does not display the allocation page. The page remains the same.
The survey does not get downloaded to the mobile device

Cannot reproduce the issue in local environment

Workaround:
Create Survey and save.
Browse to survey list, select draft tab
select survey to publish and click finalise
the allocation page will be displayed, click publish

**Comment by anandeswara** [comment]
The workaround for now, is to publish from the survey list page

**Comment by fvicino** [comment]
thanks I updated the comment with steps for the workaround

**Comment by anandeswara** [comment]
Resolved with code fix in build.html.erb
