### ISSUE TITLE
Cannot see questions when opening a published survey for edit

### ISSUE THREAD

**Issue by fvicino** [khyateh/lumstic-web#6]
In survey web, after opening a published survey to disable a multi-record question the list of questions were not displayed.
Tried un-publish the survey, the questions still do not show on the screen 

Steps:
1. Create survey publish the survey
2. Sync the survey to mobile
3. Attempt to edit the published survey

Result:
Cannot see any existing questions in the survey edit page

**Comment by anandeswara** [comment]
Resolved with changes to option model
